### ISSUE TITLE
Extra svg tags?

### ISSUE THREAD

**Issue by shoesforindustry** [edenspiekermann/sprite.sh#13]
I seem to be getting an extra svg element within the symbol, not sure if this is required?

``` xml
<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
  <symbol id='phone' viewBox='0 0 512 512'>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
      ...etc...
    </svg>
  </symbol>
  <symbol id='phone' viewBox='0 0 512 512'>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
      ...etc...
    </svg>
  </symbol>
</svg>
```

I was expecting it to output:

``` xml
<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
  <symbol id='phone' viewBox='0 0 512 512'>
    ...etc...
  </symbol>
  <symbol id='email' viewBox='0, 0, 512, 512'>
    ...etc...
  </symbol>
</svg>
```

**Comment by KittyGiraudel** [comment]
Hello. spritesh does not clean up your initial SVG files. It basically only deal with concatenating (and `viewBox` and `id` attributes). To match your expected output, simply remove the `svg` tags from your original files. :)

**Comment by shoesforindustry** [comment]
I'm not sure I understand,  my original SVG files are like the one below and as they should be?

``` xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0, 0, 512, 512">
...etc..
</svg>
```

I was expecting the SVG element to be removed for each symbol when creating the sprite file and add a wrapping SVG element around all symbols ad per my previous post.

I cannot remove the SVG from the original SVG file, otherwise it is no longer a SVG file.

**Comment by KittyGiraudel** [comment]
If you only plan on using these SVG as part of the sprite, you can totally remove the `svg` wrapping element, as they won’t be used on their own. In any case, the Bash script cannot strip the SVG tag, I’m sorry.

PS: I think commas are not allowed in `viewBox` attribute.

**Comment by KittyGiraudel** [comment]
Won’t fix, unfortunately. Closing!

**Comment by shoesforindustry** [comment]
Hugo, thanks for all your help, great project!

It is actually not that hard to automatically remove the surplus SVG elements automatically, if you run `svgo` with the `--pretty` option e.g.
`svgo --disable=cleanupIDs --enable=removeDimensions --pretty ... etc`

Then you can be sure? that the first and last line of the svg are the lines you want to remove, eg.
First: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0, 0, 512, 512">`
Last: `</svg>`

You can then use `sed` to remove these lines before adding them into a sprite, of course do this after you've got your viewBox data from the SVG ;-)

Another thing we also wanted to do was (before you call the above) generate a PNG of the SVG (as fallback) and compress it, for which we just use `rsvg-convert` and `optipng`

After the sprite file has been created we re-run the svgo stuff  (without --pretty) to create nice single valid SVG's again. We tend to keep the fallback PNG's, individual SVG's and the sprite file in the same folder.

it could so we some tydying up, but in your main loop we have:

``` bash
main ()
{
  for f in $SRC_FOLDER/*.svg; do
    if [ -f $f ]; then

      NAME=$(basename $f .svg)

      # Added code to create png's from svg and compress them
      #  RSVG (rsvg-convert) convert SVG to PNG with transparancy (brew install rsvg-convert)
      RSVG="/usr/local/bin/rsvg-convert" 
      # OptiPNG compresses and optimises PNG (brew install optipng)
      OPTIPNG="/usr/local/bin/optipng"

      if [ -e "${RSVG}" ]; then 
        echo " - Creating '"${filename}.png "'from '"${NAME}.svg"'"
        rsvg-convert -a $f > $SRC_FOLDER/${NAME}.png
        if [ -e "${OPTIPNG}"  ]; then 
          echo " - Compressing '"${NAME}.png"'"
          optipng $SRC_FOLDER/${NAME}.png --quiet --clobber 
        else 
          echo " - WARNING: Cannot find '"${OPTIPNG}"', cannot compress PNG's"
        fi

        else 
        echo " - WARNING: Cannot find '"${RSVG}"', cannot create PNG's from SVG's"
      fi

      # Original code
      VIEWBOX=${VIEWBOX_SIZE:-$(sed -n -E 's/.*viewBox="([^"]+)".*/\1/p' $f)}

      #Remove the surplus SVG tags - we know they are first & last because we ran svgo with '--pretty'
      echo " - Removing surplus SVG tags for "${DEST_FILE}
      sed '1d' $SRC_FOLDER/${NAME}.svg > $SRC_FOLDER/${NAME}.bak
      sed '$d' $SRC_FOLDER/${NAME}.bak > $SRC_FOLDER/${NAME}.svg
      rm $SRC_FOLDER/${NAME}.bak

      # Original code
      echo_verbose "Processing \`$f\` (viewBox \`$VIEWBOX\`)…"
      echo "<symbol id='$ID_PREFIX$NAME' viewBox='$VIEWBOX'>$(cat $f)</symbol>" >> $DEST_FILE

    fi
    echo "--------------------------------"
  done

  if [ -f ${DEST_FILE} ]; then
    awk 'BEGIN{print "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" style=\"display:none\">"}{print}END{print "</svg>"}' $DEST_FILE > .spritesh && mv .spritesh $DEST_FILE
  fi
}
```

We'd then call it all with a small bash file {

``` bash
#!/bin/bash
DIR="$( cd "$( dirname "$0" )" && pwd )" 
cd  "${DIR}"
svgo --disable=cleanupIDs --enable=removeDimensions --pretty -f /source/svg -o /dest/images 
&& ./spritesh -i ../images -o /dest/svg-sprites.svg 
&& svgo --disable=cleanupIDs --enable=removeDimensions -q -f /source/svg -o /dest/images
```

Thanks again,
Russ

**Comment by KittyGiraudel** [comment]
Hey Russ,

I’ll be having a closer look at this tomorrow and will get back to you with a detailed answer. Thank you for your time. :)
