### ISSUE TITLE
SVG version and aria hidden

### ISSUE THREAD

**Issue by shoesforindustry** [edenspiekermann/sprite.sh#14]
The code urrently outputs
`<svg xmlns="http://www.w3.org/2000/svg" style="display:none">`

I was thinking adding the version and 'xmlns:xlink' and perhaps aria-hidden="true"? 
e.g.
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display:none"  aria-hidden="true">`

This is just for the main svg tag.

**Comment by KittyGiraudel** [comment]
Hello.

`aria-hidden` is not necessary given that the svg has `display: none`. Regarding `xmlns` and `version`, are they necessary? Is there a point in adding them? Did you face an issue where it didn’t work properly without?

**Comment by shoesforindustry** [comment]
I pretty sure I did have some problems in the past without the `xmlns` and `version`. Most other examples of svg sprite files I have seen have then, although I can't find an article on why but I don't think it can hurt?
OK with not having the 'aria-hidden'.

**Comment by KittyGiraudel** [comment]
I’m fine with adding the xmlns and version. I’ll create a patch.

**Comment by KittyGiraudel** [comment]
PR pending: https://github.com/edenspiekermann/sprite.sh/pull/15/files.

**Comment by KittyGiraudel** [comment]
I asked @SaraSoueidan about this. Here is her answer:

> version is not needed at all and xmlns:xlink is only needed when you have any kind of links — internal or external — inside the SVG. If you don't know what the user will be using, I recommend adding xmlns:xlink to be on the safe side so their code does not break

I’ll remove `version` from the PR.

**Comment by SaraSoueidan** [comment]
👍🏻

**Comment by shoesforindustry** [comment]
👍🏻

**Comment by KittyGiraudel** [comment]
Done in https://github.com/edenspiekermann/sprite.sh/releases/tag/1.0.10.
