### ISSUE TITLE
Pipe files 

### ISSUE THREAD

**Issue by raphaelokon** [edenspiekermann/sprite.sh#21]
Hi.

Would it be possible to pipe files into sprite.sh?

Cheers

**Comment by KittyGiraudel** [comment]
Hello.

Unfortunately I don’t have time to work on that, but if you feel like making a PR to allow piping files while keeping existing API, I’m all for it. :)

**Comment by raphaelokon** [comment]
Sure. The addition is quite simple.

**Comment by KittyGiraudel** [comment]
I‘ll close this for now. :)
