### ISSUE TITLE
Gradients not visible

### ISSUE THREAD

**Issue by scriptex** [edenspiekermann/sprite.sh#23]
Hello and thanks for the awesome tool.
I have a minor issue when a svg is using a gradient defined in `defs`.
The issue is caused by the `display: none` style set to the svg sprite and prevents the gradients from showing therefore making the svg unusable.
A workaround for this is to replace the `display: none` style with something like `width: 0; height: 0; position: absolute; visibility: hidden;`.
I can submit a PR if you are interested in changing this.

**Comment by KittyGiraudel** [comment]
Hello!

Thank you for reporting this issue. I wasn’t aware of that. I actually never used gradients in icons. I’m worried about changing `display: none` into something else as it could have effect on screen readers. Wouldn’t it?

**Comment by scriptex** [comment]
Wow, fast response! 

I am pretty sure that adding `aria-hidden="true"` would prevent the screen reader from reading it. What do you think?

**Comment by KittyGiraudel** [comment]
I guess. Can you confirm that using your suggestion instead of `display: none` fixes the problem?

**Comment by scriptex** [comment]
Here are two pens from codepen which I found earlier - they show how `display` affects the rendering of gradients. I hope these are sufficient, if not I will try to do an extended research when i have more time.


https://codepen.io/jakobud/pen/KpBdjM


https://codepen.io/jakobud/pen/ZGjbde


Source: https://github.com/emilbjorklund/svg-weirdness/issues/12

**Comment by KittyGiraudel** [comment]
Good enough for me! Feel free to PR. :)

**Comment by KittyGiraudel** [comment]
Fixed in https://github.com/edenspiekermann/sprite.sh/releases/tag/1.2.1.
